version: "3.1"

services:
  postgres_db:
    image: postgres
    container_name: inlocco_container
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - 5432:5432
